# Generated by Django 5.2.7 on 2025-11-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('phno', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'userData',
            },
        ),
    ]
